global:
  openshift: true
  spire:
    jwtIssuer: https://oidc-discovery.$APP_SUBDOMAIN
  telemetry:
    prometheus:
      enabled: true

spire-server:
  tornjak:
    image:
      registry: ghcr.io
      repository: spiffe/tornjak-backend
      tag: ubi-v1.4.1
    ingress:
      enabled: true
      annotations:
        route.openshift.io/termination: "edge"
      hosts:
        - host: spire-tornjak-backend.$APP_SUBDOMAIN
          paths:
            - path: /
              pathType: Prefix
  nodeAttestor:
    k8sPsat:
      serviceAccountAllowList: ["spire-system:spire-agent"]
  notifier:
    k8sbundle:
      namespace: spire-system
  podSecurityContext:
    runAsUser: null
    runAsGroup: null
    fsGroup: null

  ingress:
    enabled: true
    annotations:
      route.openshift.io/termination: "passthrough"
    hosts:
      - host: spire-server.$APP_SUBDOMAIN
        paths:
          - path: ''
            pathType: ImplementationSpecific


spire-agent:
  podSecurityContext:
    runAsUser: null
    runAsGroup: null
    fsGroup: null

upstream-spire-agent:
  podSecurityContext:
    runAsUser: null
    runAsGroup: null
    fsGroup: null

spiffe-oidc-discovery-provider:

  podSecurityContext:
    runAsUser: null
    runAsGroup: null
    fsGroup: null
  securityContext:
    allowPrivilegeEscalation: true
    runAsNonRoot: false
    privileged: true
  ingress:
    enabled: true
    annotations:
      route.openshift.io/termination: "edge"
    hosts:
      - host: oidc-discovery.$APP_SUBDOMAIN
        paths:
          - path: /
            pathType: Prefix

tornjak-frontend:
  apiServerURL: https://spire-tornjak-backend.$APP_SUBDOMAIN/
  workingDir: /opt/app-root/src
  image:
    registry: ghcr.io
    repository: spiffe/tornjak-frontend
    tag: ubi-v1.4.1
  ingress:
    enabled: true
    annotations:
      route.openshift.io/termination: "edge"
    hosts:
      - host: spire-tornjak.$APP_SUBDOMAIN
        paths:
          - path: /
            pathType: Prefix
  podSecurityContext:
    runAsUser: null
    runAsGroup: null
    fsGroup: null

spiffe-csi-driver:
  csiDriverLabels:
    security.openshift.io/csi-ephemeral-volume-profile: restricted
  initContainers:
    - terminationMessagePath: /dev/termination-log
      name: set-context
      command:
        - chcon
        - '-Rvt'
        - container_file_t
        - spire-agent-socket/
      securityContext:
        capabilities:
          drop:
            - all
        privileged: true
      imagePullPolicy: Always
      volumeMounts:
        - name: spire-agent-socket-dir
          mountPath: /spire-agent-socket
      terminationMessagePolicy: File
      image: 'registry.access.redhat.com/ubi9:latest'
